language: node_js
node_js:
  - '6'
  - '7'
env:
  - CXX=g++-4.8
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libstdc++-4.9-dev
